name: Global CI

on: ["push", "pull_request"]

jobs:
  e2e:
    uses: trustification/trustify-ci/.github/workflows/global-ci.yml@main
    with:
      operator_bundle: "ghcr.io/trustification/trustify-operator-bundle:latest"
      run_api_tests: true
      run_ui_tests: false
      api_tests_ref: ${{ github.event.number && format('refs/pull/{0}/merge', github.event.number) || '' }}
